### ISSUE TITLE
Chore: fix or close dependancy PRs

### ISSUE THREAD

**Issue by 0xBasically** [yearn/web-lib#299]
https://github.com/yearn/web-lib/pull/298
https://github.com/yearn/web-lib/pull/295
https://github.com/yearn/web-lib/pull/293
https://github.com/yearn/web-lib/pull/292
https://github.com/yearn/web-lib/pull/290

**Comment by karelianpie** [comment]
Closing as we'll remove the docs and playground packages with https://github.com/yearn/web-lib/pull/300

Once that's done all these dependabot can be closed, there's only one left which we can address later on

**Comment by 0xBasically** [comment]
ok thanks
