### ISSUE TITLE
tabs in unusual places

### ISSUE THREAD

**Issue by antazoey** [yearn/web-lib#306]
There are tabs in unusual places throughout this code base.

For example, in the README [here](https://github.com/yearn/web-lib/blob/main/README.md#how-to-use)
and [here](https://github.com/yearn/web-lib/blob/main/packages/web-lib/contexts/WithYearn.tsx#L11), separating `function` and `WithYearn`.

**Comment by karelianpie** [comment]
It's just @Majorfi's style :)

**Comment by antazoey** [comment]
<img width="1285" alt="Screenshot 2023-09-05 at 07 33 34" src="https://github.com/yearn/web-lib/assets/19540978/20b55f71-1a5e-4e37-a6a1-9a1fd565d8b5">

> style

what

**Comment by karelianpie** [comment]
> what

I know :D @Majorfi feel free to justify yourself

**Comment by antazoey** [comment]
is there a style-court? I would love a jury for this

**Comment by antazoey** [comment]
> People should start to love stuff being aligned.

Oh, I get it now actually.
