### ISSUE TITLE
[@yearn/web-lib Feature] New Component - TokenCard

### ISSUE THREAD

**Issue by Majorfi** [yearn/web-lib#4]
# What
Adding a new `TokenCard` Component to handle the Token/Value information, similar to the one available on the yearn.finance app.
This should take the [StatisticCard](https://github.com/yearn/web-template/blob/main/pages/doc/components/statistic-card.tsx) as inspiration.
Params should be, at least, the Image source, the label and the value. A callback should be provided onClick.

<img width="326" alt="Capture d’écran 2022-04-15 à 15 36 16" src="https://user-images.githubusercontent.com/90963895/163577614-66ee55fa-c65f-4034-a647-c9a9ea0ca207.png">
<img width="326" alt="Capture d’écran 2022-04-15 à 15 36 11" src="https://user-images.githubusercontent.com/90963895/163577617-6dead8e2-1991-4c63-a75e-f05ef5946e6d.png">

**Comment by edwinzhng** [comment]
I can take this!
