### ISSUE TITLE
Doc: Add css system explanation

### ISSUE THREAD

**Issue by Majorfi** [yearn/web-lib#71]
- [ ] Short explanation over Tailwindcss, postcss, etc.
- [ ] Short explanation over css variables
- [ ] Explanation over HSL colors
- [ ] Explanation over color themes for Yearn (`light`, `dark`, `macarena`, `next`) (`next` is new default)
- [ ] Naming convention for css classname (`.yearn--[component]-[exta]`)

**Comment by MarcoWorms** [comment]
on it!

**Comment by MarcoWorms** [comment]
I did not prioritize this one properly in the past weeks but working on it now :)

**Comment by MarcoWorms** [comment]
wip here https://github.com/MarcoWorms/web-lib/tree/css-docs
