### ISSUE TITLE
Doc: Add `Example` section

### ISSUE THREAD

**Issue by Majorfi** [yearn/web-lib#72]
Create a new `Example` section with some basic examples. No complex ones

**Comment by Sprinkles1113** [comment]
Do you still need this documentation section completed?

**Comment by MarcoWorms** [comment]
Yes this is still needed @Sprinkles1113 feel free to tackle it!

**Comment by Hipsterman** [comment]
Mind if I give this a shot and see if I can generate some helpful examples?
